* TinyFlow stdcells simulations script (Spice)
*=========================================================================
* Authors : Parker Schless (generated by tinyflow-ngspice)
* Date    : {{ date }}
*=========================================================================

* Set parameters and include cell library
.param SUPPLY=1.8
.lib '{{ tech_lib_path }}' ff
.temp 125
.inc {{ cell_lib_path }}

* VDD source
Vdd VDD 0 SUPPLY

* Output load
Cl Y 0 {{ cload }}

* Input stimuli
{% for input_pin, stimulus in input_stimuli.items() -%}
Vin{{ loop.index }} {{ input_pin }} 0 PWL({{ stimulus }})
{% endfor %}

* Instantiate circuit
XU1 {{ cell_pins|join(' ') }} VDD 0 {{ cell }}

* Simulation control
.control
  set wr_vecnames
  tran 1ps {{ sim_time }}
  {% for input_pin in input_stimuli.keys() %}
  echo "Measuring delays for input pin {{ input_pin }}"
  meas tran t_pdf TRIG v({{ input_pin }}) VAL=0.9 RISE=1 TARG v(Y) VAL=0.9 FALL=1 FROM=1ns
  meas tran t_pdr TRIG v({{ input_pin }}) VAL=0.9 FALL=1 TARG v(Y) VAL=0.9 RISE=1 FROM=1ns
  {% endfor %}
  wrdata {{ output_dir }}/{{ output_basename }}.csv {% for input_pin in input_stimuli.keys() %}V({{ input_pin }}) {% endfor %}V(Y)
  quit
.endc

.end
